# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - git config user.name "Wiki Sync"
  - git config user.email "fvtt-travisci@mail.com"
  - git remote remove origin
  - git remote add origin https://$GITLAB_API_KEY@gitlab.com/foundry-vtt-community/wiki.git > /dev/null 2>&1
  - git remote add upstream https://$GITLAB_API_KEY@gitlab.com/foundry-vtt-community/wiki.wiki.git > /dev/null 2>&1
  - git fetch origin
  - git fetch upstream
  - git merge upstream/master --no-edit

deploy1:
  stage: deploy
  script:
    - git push origin HEAD:master
    - git push upstream HEAD:master
