script:
- |
  git config user.name "Wiki Sync"
  git config user.email "fvtt-travisci@mail.com"
  git remote remove origin
  git remote add origin https://$GITHUB_API_KEY@github.com/foundry-vtt-community/wiki.git > /dev/null 2>&1
  git remote add upstream https://$GITHUB_API_KEY@github.com/foundry-vtt-community/wiki.wiki.git > /dev/null 2>&1
  git fetch origin
  git fetch upstream
  wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc
  chmod a+x gh-md-toc
  ./gh-md-toc https://github.com/foundry-vtt-community/wiki/wiki > _Sidebar.md
  ls -la
  more _Sidebar.md
  git merge upstream/master --no-edit
  git push origin HEAD:master > /dev/null 2>&1
  git push upstream HEAD:master > /dev/null 2>&1
env:
  matrix:
    secure: V6RhejfhOSmkSPLCDewCmXOf2L25Q2MutnyK+pZf6o9x5A+Ji6OPI3XNLvpPuRtP3WNYDzwpq0unhDnJO/vWPXlCoIcKT3FLJrBhu5lctsxTzCj2zoVH4nQgmiGUmuPBjoRy6Fl160igYKyKZ7gQGrLAw8l3LUzUN1lsB6z7w4BDSKTdZUckqo/Ks7o+I814Owl4WOQL5xbTrL8GTiotlGvhM1xY+B0aeoYwkRUf9/Fpf0Ftr5aO4wXjs0MD8ckBs36CPt8JxopaQ3izCdW+p2zVJWQwNf+bsVUsMmHckdDx4E4p0TyMTdo1DMvqFdjrEVxv4AlzXEg09PP1PnHaSKwHm3/VhpXI+nBzLUQtcxFWsFgKD3SjuXr5ckjojlD2ihInH1Iwd2KFEftDfI72nErtCLpSLmbIs9c9ve19UXw5PPCYE6L27ERc0CZC3MutEE1OSisd+j219tFxojNSrP3sLOFQkHPjxv+XWrK5sRUHPLaAyzbfiXhm6WktKowfnKwMvK6moYx1It2HIvA/KLz/+NEzAwuAm0Io7dMVMI92znzCTbGgQPIP+wwZXzk14U80r0kn+wOUZS41DFOrK2yDpNZJa/tqJh15l/qBUkmXxYP+36A9vsDiPp5cyi5Br16VisshzQyd/S+pYTZViLy7gJ0mKaGeabEyLo207XA=
